name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Doniyor1912
          outputs: |
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light
            dist/snake-colored.svg?color_snake=#ff6600&color_dots=#00ccff

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*.svg"
          message: "update snake animation"
          default_author: github_actions
